# Dependencies
markdown:         kramdown
highlighter:        rouge

# Permalinks
permalink:        pretty

# Setup
title:            Frank 
tagline:          '  Everything is gonna be ðŸ’€ '
description:      ':) Interested in Code & Life & Philosophy & Story & Travel'
url:              https://frank-cq.github.io

excerpt_separator: '<!--more-->'

author:
  name:           'Frank'
  url:            https://frank-cq.github.io
  github:          frank-cq
  stackoverflow:   frank
  csdn:            'alading2009'
  jianshu:         'ä¼šè¡Œèµ°çš„ä¸¤è„šä¹¦æ©±'
  email:           'chenqingse[at]outlook[dot]com'
  bokeyuan:        'å¤œè¯»æ˜¥ç§‹'

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/frank-cq/frank-cq.github.io

# Gems
plugins: [jekyll-paginate]
